# Order
jobs:
  - config: configs/Simon/spot_to_sphere.yaml
    sentinel: output/spot/sphere/ep049/ep049_render.png 
    extra_args: ["--e2e", "--png"] 

  - config: configs/Simon/spot_to_bob.yaml
    sentinel: output/spot/bob/ep049/ep049_render.png  
    extra_args: ["--e2e", "--png"]  

  - config: configs/Simon/spot_to_bunny.yaml
    sentinel: output/spot/bunny/ep049/ep049_render.png  
    extra_args: ["--e2e", "--png"]  

  - config: configs/Simon/spot_to_bebe.yaml
    sentinel: output/spot/bebe/ep049/ep049_render.png 
    extra_args: ["--e2e", "--png"] 