# Order
jobs:
  - config: configs/Manish/bob_to_sphere.yaml
    sentinel: output/bob/sphere/ep049/ep049_render.png 
    extra_args: ["--e2e", "--png"] 

  - config: configs/Manish/bob_to_spot.yaml
    sentinel: output/bob/spot/ep049/ep049_render.png  
    extra_args: ["--e2e", "--png"]  

  - config: configs/Manish/bob_to_bunny.yaml
    sentinel: output/bob/bunny/ep049/ep049_render.png  
    extra_args: ["--e2e", "--png"]  

  - config: configs/Manish/bob_to_bebe.yaml
    sentinel: output/bob/bebe/ep049/ep049_render.png 
    extra_args: ["--e2e", "--png"] 

    extra_args: []