# 3DGS Shape Morphing setting file

# Input/Output file path
input_mesh_path: "assets/bunny.obj"
target_mesh_path: "assets/bunny.obj"
output_dir: "output/"

# ===================================================================
# DiffMPM for Shape Morphing setting
# ===================================================================
simulation:
  # Grid setting
  grid_dx: 1                             # Grid cell size (CRITICAL for AABB radius)
  points_per_cell_cuberoot: 2            # Number of points per cell (cubic root)
  grid_min_point: [-16.0, -16.0, -16.0]  # Grid minimum coordinate
  grid_max_point: [16.0, 16.0, 16.0]     # Grid maximum coordinate
  
  # Material properties (Lame parameters)
  lam: 38888.89                   # λ (Volume elastic modulus)
  mu:  58333.3                    # μ (Shear elastic modulus)
  density: 75.0                   # Density
  
  # Simulation parameters
  dt: 0.00833333333               # Time step (1/120)
  drag: 0.5                       # Drag coefficient
  external_force: [0.0, 0.0, 0.0] # External force (gravity, etc.)
  smoothing_factor: 0.955         # Smoothing factor

# Optimization setting
optimization:
  num_animations: 1              # Number of animation episodes
  num_timesteps:  10              # Number of time steps per episode
  control_stride: 10              # Control frame interval
  max_gd_iters: 1                 # Maximum number of gradient descent iterations
  max_ls_iters: 10                # Maximum number of line search iterations
  initial_alpha: 0.01             # Initial step size
  gd_tol: 0.0001                  # Gradient tolerance

# Output setting
output:
  export_ply: false               # Export PLY file
  output_format: "ply"            # Output format

# ===================================================================
# UPSAMPLING SETTINGS (RUNTIME SURFACE)
# ===================================================================
sampling:
  runtime_surface:
    # Surface detection (extract surface from volumetric point cloud)
    use_surface_detection: true   # Enable surface detection (volumetric → surface)
    k_surface: 36                 # CRITICAL for thin structures (ears, legs)! Default: 24
    thr_percentile: 8.0           # More strict: only top 92% (was 10.0 = top 90%) - cleaner surface
    soft_tau: 0.08                # Slightly sharper transition (was 0.10) - more confident surface
    hysteresis: 0.03              # Hysteresis for temporal stability
    ema_beta: 0.95                # Exponential Moving Average weight
    
    # Sampling configuration
    M: 180000                     # Slightly fewer points = less noise (was 200000)
    use_stratified_sampling: true   # Stratified sampling for uniform distribution
    surf_jitter_alpha: 0.20       # Even less jitter for cleaner result (was 0.25)
    thickness: 0.08               # Thinner shell = more focused surface (was 0.10)
    density_gamma: 2.5            # Density distribution adjustment
    
    # Gaussian rendering
    sigma0: 0.08                  # Gaussian base scale (larger = better coverage)
    differentiable: true          # Enable differentiable operations
    ed:
      enabled: true               # Enable/disable the Embedded Deformation graph.
      num_nodes: 180              # Number of nodes in the deformation graph.
      node_knn: 8                 # Number of neighboring nodes to connect for each graph node (k-NN).
      point_knn_nodes: 8          # Number of nearest graph nodes each point connects to.
      lambda_lap: 1.0e-2          # Weight for Laplacian regularization (for graph smoothness)..
    # Post-processing
    post_equalize:
      enabled: true               # Enable density equalization
      use_multiscale: false       # Disable multi-scale (can cause grid patterns)
      iters: 12                   # More iterations for cleaner edges (was 10)
      k: 32                       # More neighbors for better smoothing (was 24)
      step: 0.50                  # Stronger repulsion to spread outliers (was 0.35)
      radius_mul: 1.3             # Slightly larger radius (was 1.2)
      project_to_shell: true      # Project points back to surface shell
      remove_outliers: true       # Statistical outlier removal
      outlier_std_ratio: 1.3      # VERY AGGRESSIVE: 1.3*std (was 1.5) - removes edge artifacts
      radius_outlier_removal: true  # Additional radius-based filtering
      radius_multiplier: 2.5      # More strict: 2.5x median (was 3.0) - removes isolated points
    
    laplacian_smooth:
      enabled: false              # Laplacian smoothing (optional, set true if needed)
      iters: 5
      lambda_smooth: 0.5
    
    normal_smooth:
      # Pre-smoothing: Applied to LOW-RES normals BEFORE upsampling
      # This is the KEY to consistent normals - smooth the source, not the result!
      enabled: true               # Enable pre-smoothing of low-res normals
      iters: 10                   # More iterations on low-res (cheaper, more effective)
      lambda_smooth: 0.8          # Strong smoothing at low-res level
      k_neighbors: 32             # More neighbors for robust averaging
      geometry_aware: true        # NEW: Use spatial distance weighting (preserves thin structures)
      spatial_sigma: 1.5          # Gaussian bandwidth multiplier (smaller = more local)
    
    post_normal_smooth:
      # Post-smoothing: Applied to UPSAMPLED normals (optional light cleanup)
      enabled: true               # Enable for thin structure cleanup (legs, ears)
      iters: 3                    # Light cleanup for high-res
      lambda_smooth: 0.4          # Gentle smoothing
      k_neighbors: 20
      geometry_aware: true        # Preserve thin structures
      spatial_sigma: 1.2          # More local than pre-smoothing
    
    adaptive_sigma:
      enabled: false              # Adaptive covariance scaling (optional)
      min_scale: 0.5
      max_scale: 2.0

# ===================================================================
# RENDER SETTINGS (RUNTIME RENDERER)
# ===================================================================
render:
  num_frames: 1         
  schedule: uniform       # or uniform (0..T-1 uniformly sample)
  bg: [1.0, 1.0, 1.0]     # bg color (RGB 0-1)
  particle_color: [0.27, 0.51, 0.71]  # particle color (RGB 0-1)
  
  lighting:
    model: phong                       # Lambertian or Phong
    type: directional                  # or "point"
    direction: [0.3, -0.5, 0.8]        # directional
    two_sided: true                    # essential: remove artifacts
    ambient: 0.18                      # recommended to slightly increase from default 0.10
    diffuse: 0.85
    specular: 0.10
    shininess: 32
    
camera:
  width:  3840
  height: 2160
  fx: 1425.0                           # Focal length in pixels X 
  fy: 1425.0                           # Focal length in pixels Y 
  cx: 1920.0                           # Principal point X 
  cy: 1080.0                           # Principal point Y
  znear: 0.01
  zfar: 100.0
  lookat:
    eye:    [20.0,  -25.0,  15.0]      # camera position (behind origin on -Z side)
    target: [ 0.0,    0.0,   0.0]      # look at the origin
    up:     [ 0.0,    0.0,   1.0]      # Up vector

