# 3DGS Shape Morphing setting file

# Input/Output file path
input_mesh_path: "assets/bunny.obj"
target_mesh_path: "assets/bunny.obj"
output_dir: "output/"

# ===================================================================
# DiffMPM for Shape Morphing setting
# ===================================================================
simulation:
  # Grid setting
  grid_dx: 1                             # Grid cell size (CRITICAL for AABB radius)
  points_per_cell_cuberoot: 2            # Number of points per cell (cubic root)
  grid_min_point: [-16.0, -16.0, -16.0]  # Grid minimum coordinate
  grid_max_point: [16.0, 16.0, 16.0]     # Grid maximum coordinate
  
  # Material properties (Lame parameters)
  lam: 38888.89                   # λ (Volume elastic modulus)
  mu:  58333.3                    # μ (Shear elastic modulus)
  density: 75.0                   # Density
  
  # Simulation parameters
  dt: 0.00833333333               # Time step (1/120)
  drag: 0.5                       # Drag coefficient
  external_force: [0.0, 0.0, 0.0] # External force (gravity, etc.)
  smoothing_factor: 0.955         # Smoothing factor

# Optimization setting
optimization:
  num_animations: 1              # Number of animation episodes
  num_timesteps:  10              # Number of time steps per episode
  control_stride: 10              # Control frame interval
  max_gd_iters: 1                 # Maximum number of gradient descent iterations
  max_ls_iters: 10                # Maximum number of line search iterations
  initial_alpha: 0.01             # Initial step size
  gd_tol: 0.0001                  # Gradient tolerance

# Output setting
output:
  export_ply: false               # Export PLY file
  output_format: "ply"            # Output format

# ===================================================================
# UPSAMPLING SETTINGS (RUNTIME SURFACE)
# ===================================================================
sampling:
  runtime_surface:
    # ===================================================================
    # HYBRID FAISS + FULLY DIFFERENTIABLE CONFIGURATION
    # ===================================================================
    
    # Hybrid FAISS settings (10-20x speedup + 100% differentiable)
    use_hybrid_faiss: True        # Fast FAISS + differentiable weights
    use_faiss_ivf: True           # IVF index for extra speed (10-100x)
    ivf_nlist: 100                # Number of IVF clusters
    ivf_nprobe: 10                # Number of clusters to search
    
    # Soft-radius mode (smoother gradients)
    use_soft_radius: True        # false=speed, true=quality (20-30% slower)
    soft_radius_candidates: 256   # Candidate pool: 64(fast), 128(balanced), 256(best)
    
    # Differentiability settings
    differentiable: True          # Enable differentiable operations
    sampling_tau: 0.32            # Gumbel-Softmax temperature (lower = sharper)
    knn_tau: 0.20                 # Soft kNN temperature
    surface_power: 2.2            # Surface concentration (higher = stricter)
    
    # Surface detection (extract surface from volumetric point cloud)
    use_surface_detection: True   # Enable surface detection
    k_surface: 48                 # kNN for surface detection
    thr_percentile: 5.0           # Top 95% as surface
    soft_tau: 0.08                # Sharper surface transition
    hysteresis: 0.03              # Temporal stability
    ema_beta: 0.95                # EMA weight
    
    # Sampling configuration
    M: 80000                      # Number of upsampled points
    surf_jitter_alpha: 0.32       # Surface jitter
    density_gamma: 1.8            # Density distribution adjustment
    
    # Gaussian rendering
    sigma0: 0.08                  # Gaussian base scale
    use_F_kernel: True            # Use F kernel for interpolation
    k_F: 32                       # kNN for F interpolation
    h_mul: 1.5                    # Bandwidth multiplier
    
    # Embedded Deformation graph
    ed:
      enabled: True
      num_nodes: 180
      node_knn: 8
      point_knn_nodes: 8
      lambda_lap: 1.0e-2
    
    # ===================================================================
    # POST-PROCESSING with MLS PROJECTION
    # ===================================================================
    post_equalize:
      enabled: True                    # Enable density equalization
      iters: 15                        # Reduced (MLS does heavy lifting)
      k: 36                            # kNN neighbors
      step: 0.30                       # Step size 
      radius_mul: 1.15                 # Radius multiplier
      
      # MLS Projection (removes grid patterns + internal particles)
      use_mls_projection: True         # ✓ Use MLS instead of anchor plane
      mls_iters: 5                     # MLS projection iterations
      mls_step: 1.0                    # MLS step size
    
    # Optimization flags
    use_amp: True                      # Mixed precision FP16 (2x speedup)

# ===================================================================
# RENDER SETTINGS (RUNTIME RENDERER)
# ===================================================================
camera:
  width:  3840
  height: 2160
  fx: 1425.0                           # Focal length in pixels X 
  fy: 1425.0                           # Focal length in pixels Y 
  cx: 1920.0                           # Principal point X 
  cy: 1080.0                           # Principal point Y
  znear: 0.01
  zfar: 100.0
  lookat:
    eye:    [20.0,  -25.0,  15.0]      # camera position (behind origin on -Z side)
    target: [ 0.0,    0.0,   0.0]      # look at the origin
    up:     [ 0.0,    0.0,   1.0]      # Up vector

render:
  num_frames: 1         
  schedule: uniform       # or uniform (0..T-1 uniformly sample)
  bg: [1.0, 1.0, 1.0]     # bg color (RGB 0-1)
  particle_color: [0.27, 0.51, 0.71]  # particle color (RGB 0-1)
  
  lighting:
    model: phong                       # Lambertian or Phong
    type: directional                  # or "point"
    direction: [0.3, -0.5, 0.8]        # directional
    two_sided: true                    # essential: remove artifacts
    ambient: 0.18                      # recommended to slightly increase from default 0.10
    diffuse: 0.85
    specular: 0.10
    shininess: 32

