# DiffMPM Shape Morphing setting file
# HYBRID UPSAMPLING STRATEGY APPLIED
# ===================================================================
# This configuration now supports three upsampling binding methods:
# 1. "geodesic": Original surface-aware method. Good for detail, but can cause "smearing".
# 2. "aabb": Physically-based method. Fixes smearing, but can lose fine detail.
# 3. "hybrid": The recommended approach. Uses AABB as a stable base and blends in
#              a small amount of the geodesic result to restore detail.
# ===================================================================

# Input/Output file path
input_mesh_path: "assets/isosphere.obj"
target_mesh_path: "assets/spot.obj"
output_dir: "output/"

# Simulation setting
simulation:
  # Grid setting
  grid_dx: 1                             # Grid cell size (CRITICAL for AABB radius)
  points_per_cell_cuberoot: 2            # Number of points per cell (cubic root)
  grid_min_point: [-16.0, -16.0, -16.0]  # Grid minimum coordinate
  grid_max_point: [16.0, 16.0, 16.0]     # Grid maximum coordinate
  
  # Material properties (Lame parameters)
  lam: 38888.89                   # λ (Volume elastic modulus)
  mu:  58333.3                    # μ (Shear elastic modulus)
  density: 60.0                   # Density
  
  # Simulation parameters
  dt: 0.00833333333               # Time step (1/120)
  drag: 0.5                       # Drag coefficient
  external_force: [0.0, 0.0, 0.0] # External force (gravity, etc.)
  smoothing_factor: 0.955         # Smoothing factor

# Optimization setting
optimization:
  num_animations: 45              # Number of animation episodes
  num_timesteps: 10               # Number of time steps per episode
  control_stride: 10              # Control frame interval
  max_gd_iters: 1                 # Maximum number of gradient descent iterations
  max_ls_iters: 10                # Maximum number of line search iterations
  initial_alpha: 0.01             # Initial step size
  gd_tol: 0.0001                  # Gradient tolerance

# Output setting
output:
  export_ply: false               # Export PLY file
  output_format: "ply"            # Output format

# ===================================================================
# UPSAMPLING SETTINGS (MODIFIED FOR HYBRID STRATEGY)
# ===================================================================
sampling:
  enabled: true
  binding_method: "hybrid"        # "hybrid", "aabb", or "geodesic"
  hybrid_alpha: 0.15              # Blending factor (0.0 to 1.0). Used only in "hybrid" mode.
                                  # Represents the influence of the geodesic result.
  
  # --- Common Settings ---
  count: 150000     # M: Number of upsampled surface points
  frames_to_sample: 1
  mode: polarRU     # "polarRU" is recommended for stability
  sigma0: 0.02
  ptsize: 0.05

  # --- AABB Method Settings ---
  aabb_settings:
    # Radius for neighbor search = grid_dx * radius_factor.
    radius_factor: 2.5
    # Fallback search radius multipliers for empty cells.
    fallback_expansion_factors: [1.5, 2.0]
    # K for the final k-NN fallback if a point is still isolated.
    # Also used as the shape of the binding matrix (M, K).
    K: 14 

  # --- Geodesic Method Settings ---
  geodesic_settings:
    knn_k: 14         # K for blending (should match aabb_settings.K)
    k_graph: 32       # Graph degree for Dijkstra
    N_anchor: 8       # Number of Euclidean anchors
    candidate_factor: 8
    tau: null         # null -> auto from base spacing
    alpha_band: 1.5
    theta0_deg: 56.0
    beta_normal: 2.2
    cos_n_thr: 0.60
    dir_thr: 0.50
    penalty: 60.0
    r_geo_factor: 8.0