# Order
jobs:
  - config: configs/Chayo/sphere_to_bob.yaml
    sentinel: output/bob/ep049/ep049_render.png 
    extra_args: ["--e2e", "--png"] 

  - config: configs/Chayo/sphere_to_spot.yaml
    sentinel: output/spot/ep049/ep049_render.png  
    extra_args: ["--e2e", "--png"]  

  - config: configs/Chayo/sphere_to_bunny.yaml
    sentinel: output/bunny/ep049/ep049_render.png  
    extra_args: ["--e2e", "--png"]  

  - config: configs/Chayo/sphere_to_bebe.yaml
    sentinel: output/bebe/ep049/ep049_render.png 
    extra_args: ["--e2e", "--png"] 

    extra_args: []

  # - config: configs/your_next.yaml
  #   tag: myexp
  #   sentinel: output/some/final_artifact.ply
